name: 'Composer (action)'
description: 'Use the Composer CLI in your Github Actions.'

inputs:
  composer_version:
    description: "What version of Composer to use"
    default: latest
    required: false

  command:
    description: "Composer command to run"
    required: true
    default: install

  args:
    description: "Command line arguments to composer"
    required: false
    default: "--optimize-autoloader"

runs:
  using: "composite"
  steps:
    - env:
        COMPOSER_VERSION: ${{ inputs.composer_version }}
        COMPOSER_COMMAND: ${{ inputs.command }}
        COMPOSER_ARGS: ${{ inputs.args }}
      run: |
        set -ex
        id
        env | sort
        echo VERSION: ${{ inputs.composer_version }}
        docker run -v $GITHUB_WORKSPACE:/src -w /src --rm \
          composer:$COMPOSER_VERSION $COMPOSER_COMMAND $COMPOSER_ARGS
      shell: bash

branding:
  icon: 'package'
  color: 'purple'
