name: 'PHP Composer'
description: 'Use the Composer CLI in your Github Actions.'

inputs:
  composer_version:
    description: "What version of Composer to use"
    default: latest
    required: false

  command:
    description: "Composer command to run (or get_config to just get the output vars)"
    required: true
    default: install

  args:
    description: "Command line arguments to composer"
    required: false
    default: "--optimize-autoloader --no-progress"

outputs:
  composer_cache_dir:
    description: "Where composer created its cache"
    value: ${{ steps.composer_run.outputs.composer_cache_dir }}

  composer_major_version:
    description: "Major version of the composer run"
    value: ${{ steps.composer_run.outputs.composer_major_version }}

runs:
  using: "composite"
  steps:
    - env:
        COMPOSER_VERSION: ${{ inputs.composer_version }}
        COMPOSER_COMMAND: ${{ inputs.command }}
        COMPOSER_ARGS: ${{ inputs.args }}
      shell: bash
      id: composer_run
      run: |
        set -e

        # Make sure the latest version is available, pull it quietly
        docker pull -q composer:${COMPOSER_VERSION}

        # Extract the major version
        MAJOR_VERSION=$(docker run --rm composer:${COMPOSER_VERSION} --version | perl -pe '($_)=/\b(\d)\d*\.\d+\.\d+/;')
        echo "::set-output name=composer_cache_dir::${RUNNER_WORKSPACE}/composer/cache"
        echo "::set-output name=composer_major_version::${DETECT_COMPOSER_MAJOR_VERSION}"

        case "${COMPOSER_COMMAND}" in
          get_config)
            echo "output composer_cache_dir=${RUNNER_WORKSPACE}/composer/cache"
            echo "output composer_major_version=${DETECT_COMPOSER_MAJOR_VERSION}"
            exit
            ;;

          *)
            docker run --rm \
              --volume ${RUNNER_WORKSPACE}/composer:/tmp \
              --volume ${GITHUB_WORKSPACE}:/app \
              -w /app \
              composer:${COMPOSER_VERSION} $COMPOSER_COMMAND $COMPOSER_ARGS
            ;;
        esac

branding:
  icon: 'package'
  color: 'purple'
