name: Test deploy workflow 3

# Either manually started *or* triggered by an "release"
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to which to deploy the code (staging or live)'
        required: true
        default: 'staging'
  release:
    types: [published]

jobs:
  test-release:
    runs-on: ubuntu-latest

    env:
      TARGET_URL: https://neos-${{ github.event.inputs.environment }}.ptaheute.de
      ENVIRONMENT_RELEASE: 'live'
      ENVIRONMENT_PRERELEASE: 'staging'

    steps:
      - name: Checkout repository (depth=unlimited)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: "Environment chooser: Pre-Release"
        if: github.event_name == 'release' && github.event.release.prerelease
        id: environment
        run: echo "::set-output name=name::$ENVIRONMENT_PRERELEASE"

      - name: "Environment chooser: Release"
        if: github.event_name == 'release' && ! github.event.release.prerelease
        id: environment
        run: echo "::set-output name=name::$ENVIRONMENT_RELEASE"

      - name: "Environment chooser: Manual selected"
        if: github.event_name == 'workflow_dispatch'
        id: environment
        run: echo "::set-output name=name::${{ github.event.inputs.environment }}"

      - name: Print out environment name
        env:
          CHOSEN_ENVIRONMENT: ${{ steps.environment.outputs.name }}
        run: |
          echo "Chosen environment: $CHOSEN_ENVIRONMENT"
