
name: Test workflow

on:
  release:
    types: [published]

jobs:
  test-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Debug Action
        uses: hmarr/debug-action@v1.0.0

      - name: start deployment
        uses: bobheadxi/deployments@v0.4.3
        id: deployment
        with:
          step: start
          desc: ${{ github.event.release.tag_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          env: production

      - name: Show release event infos
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
          RELEASE_COMMITISH: ${{ github.event.release.target_commitish }}
          RELEASE_DRAFT: ${{ github.event.release.draft }}
          RELEASE_PRERELEASE: ${{ github.event.release.prerelease }}
          RELEASE_BODY: ${{ github.event.release.body }}
        run: |
          echo "release.tag_name=$RELEASE_TAG"
          echo "release.target_commitish=$RELEASE_COMMITISH"
          echo "release.draft=$RELEASE_DRAFT"
          echo "release.prerelease=$RELEASE_PRERELEASE"
          echo "release.body=$RELEASE_BODY"

      - name: update deployment status (success)
        uses: bobheadxi/deployments@v0.4.3
        if: ${{ success() }}
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
