name: Test deploy workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to which to deploy the code (staging or live)'
        required: true
        default: 'staging'
  release:
    types: [published]

jobs:
  test-release:
    runs-on: ubuntu-latest

    env:
      TARGET_URL: https://neos-${{ github.event.inputs.environment }}.ptaheute.de

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: altinukshini/deployment-action@releases/v1
        name: Create GitHub deployment
        id: deployment
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}
          environment: ${{ github.event.inputs.environment }}

      - name: Deploy my app
        run: |
          # add your deployment code here
          exit 1

      - name: Update deployment status (success)
        if: success()
        uses: altinukshini/deployment-status@releases/v1
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}
          environment_url: ${{ env.TARGET_URL }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          state: "success"

      - name: Update deployment status (failure)
        if: failure()
        uses: altinukshini/deployment-status@releases/v1
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}
          environment_url: ${{ env.TARGET_URL }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          state: "failure"
