
name: Test workflow

on:
  release:
    types: [published]

jobs:
  test-php:
    runs-on: ubuntu-latest

    container:
      env:
        COMPOSER_MAJOR_VERSION: 1
      image: registry.cron.eu/docker/php-ci:php-7.2
      options: --user 1001

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: check composer version
        run: composer --version

      - name: check current directory
        run: |
          pwd
          ls -la
          env

  test-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Debug Action
        uses: hmarr/debug-action@v1.0.0

      - name: Show release event infos
        env:
          RELEASE_TAG: ${{ github.release.tag_name }}
          RELEASE_COMMITISH: ${{ github.release.target_commitish }}
          RELEASE_DRAFT: ${{ github.release.draft }}
          RELEASE_PRERELEASE: ${{ github.release.prerelease }}
          RELEASE_BODY: ${{ github.release.body }}
        run: |
          echo "release.tag_name=$RELEASE_TAG"
          echo "release.target_commitish=$RELEASE_COMMITISH"
          echo "release.draft=$RELEASE_DRAFT"
          echo "release.prerelease=$RELEASE_PRERELEASE"
          echo "release.body=$RELEASE_BODY"

      - uses: avakar/create-deployment@v1
        with:
          auto_merge: false
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
