
name: Test workflow

on:
  release:
    types: [published]

jobs:
  test-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Debug Action
        uses: hmarr/debug-action@v1.0.0

      - name: Show release event infos
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
          RELEASE_COMMITISH: ${{ github.event.release.target_commitish }}
          RELEASE_DRAFT: ${{ github.event.release.draft }}
          RELEASE_PRERELEASE: ${{ github.event.release.prerelease }}
          RELEASE_BODY: ${{ github.event.release.body }}
        run: |
          echo "release.tag_name=$RELEASE_TAG"
          echo "release.target_commitish=$RELEASE_COMMITISH"
          echo "release.draft=$RELEASE_DRAFT"
          echo "release.prerelease=$RELEASE_PRERELEASE"
          echo "release.body=$RELEASE_BODY"

      - uses: avakar/create-deployment@v1
        with:
          auto_merge: false
          environment: test
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
