name: Test deploy workflow 2

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to which to deploy the code (staging or live)'
        required: true
        default: 'staging'
  release:
    types: [published]

jobs:
  test-release:
    runs-on: ubuntu-latest

    env:
      TARGET_URL: https://neos-${{ github.event.inputs.environment }}.ptaheute.de

    steps:
      - name: Checkout repository (depth=unlimited)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Test git describe tags
        run: |
          set -ex
          git describe --tags
