name: Test deploy workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to which to deploy the code (staging or live)'
        required: true
        default: 'staging'

jobs:
  test-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Show release event infos
        env:
          ENV: ${{ github.event.inputs.environment }}
          RELEASE_TAG: ${{ github.release.tag_name }}
          RELEASE_COMMITISH: ${{ github.release.target_commitish }}
          RELEASE_DRAFT: ${{ github.release.draft }}
          RELEASE_PRERELEASE: ${{ github.release.prerelease }}
          RELEASE_BODY: ${{ github.release.body }}
        run: |
          echo "env=$ENV"
          echo "release.tag_name=$RELEASE_TAG"
          echo "release.target_commitish=$RELEASE_COMMITISH"
          echo "release.draft=$RELEASE_DRAFT"
          echo "release.prerelease=$RELEASE_PRERELEASE"
          echo "release.body=$RELEASE_BODY"

      - uses: avakar/create-deployment@v1
        with:
          auto_merge: false
          environment: ${{ github.event.inputs.environment }}
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
