name: Test workflow

on:
  release:
    types: [published]

jobs:
  test_environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Debug Action
        uses: hmarr/debug-action@v1.0.0

      - name: Show release event infos
        run: |
          echo "release.tag_name=${{ github.release.tag_name }}"
          echo "release.target_commitish=${{ github.release.target_commitish }}"
          echo "release.draft=${{ github.release.draft }}"
          echo "release.prerelease=${{ github.release.prerelease }}"
          echo "release.body=${{ github.release.body }}"

      - uses: avakar/create-deployment@v1
        with:
          auto_merge: false
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
