name: Test action

on: [push]

jobs:

  test-action:
    runs-on: ubuntu-latest

    env:
      COMPOSER_VERSION: 2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Test versions
        run: |
          set -ex
          make --version || true
          docker --version || true
          aws --version || true
          php --version || true
          composer --version || true
          node --version || true
          grep VERSION= /etc/os-release || true
          git describe --tags
