name: Test action

on: [push]

jobs:

  test-action:
    runs-on: ubuntu-latest

    env:
      COMPOSER_VERSION: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Composer cache directory
        id: composer_config
        uses: ./.github/actions/composer
        with:
          composer_version: ${{ env.COMPOSER_VERSION }}
          command: get_config

      - name: Cache Composer Downloads
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer_config.outputs.composer_cache_dir }}
          key: composer-v${{ steps.composer_config.outputs.composer_major_version }}

      - name: Run our composer install action
        uses: ./.github/actions/composer
        with:
          composer_version: ${{ env.COMPOSER_VERSION }}
          action: install
