name: Test action

on: [push]

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: check composer version
        uses: .github/actions/composer
        with:
          composer_version: 1
