name: Test action

on: [push]

jobs:

  test-action:
    runs-on: ubuntu-latest

    env:
      COMPOSER_VERSION: 2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Test versions
        run: |
          set -ex
          make --version || true
          docker --version || true
          aws --version || true
          php --version || true
          composer --version || true
          node --version || true
          grep VERSION= /etc/os-release || true
          #git fetch -f origin ${{ github.ref }}:${{ github.ref }}
          git describe --tags

      - name: Get composer cache directory
        id: composer_config
        uses: ./.github/actions/composer
        #uses: baschny/php-composer-action@v1
        with:
          composer_version: ${{ env.COMPOSER_VERSION }}
          command: get_config

      - name: Cache composer downloads
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer_config.outputs.composer_cache_dir }}
          key: composer-v${{ steps.composer_config.outputs.composer_major_version }}

      - name: Run composer install
        uses: ./.github/actions/composer
        #uses: baschny/php-composer-action@v1
        with:
          composer_version: ${{ env.COMPOSER_VERSION }}
          command: install
          github_oauth: ${{ secrets.DEPLOY_TOKEN }}

      - name: Test results
        run: |
          id
          pwd
          ls -la
          ls -la Packages/Application/CRON.DavPtaheute.Frontend
